version: '3.7'

services:
fluentd:
build: ./fluentd
ports:
- "24224:24224"
- "24224:24224/udp"
volumes:
- ./fluentd/log:/fluentd/log

loki:
build: ./loki
ports:
- "3100:3100"
volumes:
- ./loki/data:/loki

kafka:
build: ./kafka
ports:
- "9092:9092"
environment:
KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

zookeeper:
image: wurstmeister/zookeeper
ports:
- "2181:2181"

wazuh:
build: ./wazuh
ports:
- "55000:55000"
- "1514:1514"
- "1515:1515"
depends_on:
- postgresql

postgresql:
image: postgres:13
environment:
POSTGRES_USER: wazuh
POSTGRES_PASSWORD: wazuhpassword
POSTGRES_DB: wazuh
volumes:
- postgresql_data:/var/lib/postgresql/data

grafana:
build: ./grafana
ports:
- "3000:3000"
volumes:
- ./grafana/data:/var/lib/grafana

metron:
build: ./metron
ports:
- "8080:8080"
depends_on:
- kafka

volumes:
postgresql_data:
